FROM mageia:7
LABEL maintainer="jacek.danecki@intel.com"

RUN dnf install -y 'dnf-command(copr)' && \
    dnf copr enable -y jdanecki/intel-opencl && \
    dnf install -y intel-opencl clinfo --setopt=install_weak_deps=False && dnf clean all
CMD ["/bin/bash"]
