FROM opensuse/tumbleweed:latest
LABEL maintainer="jacek.danecki@intel.com"

RUN zypper addrepo -r https://copr.fedorainfracloud.org/coprs/jdanecki/intel-opencl/repo/opensuse-tumbleweed/jdanecki-intel-opencl-opensuse-tumbleweed.repo && \
    zypper --no-gpg-checks  install -y  intel-opencl clinfo intel-level-zero-gpu level-zero
CMD ["/bin/bash"]
