FROM opensuse/leap:15.2
LABEL maintainer="jacek.danecki@intel.com"

RUN zypper addrepo -r https://copr.fedorainfracloud.org/coprs/jdanecki/intel-opencl/repo/opensuse-leap-15.2/jdanecki-intel-opencl-opensuse-leap-15.2.repo && \
    zypper --no-gpg-checks  install -y  intel-opencl clinfo clpeak intel-level-zero-gpu
CMD ["/bin/bash"]
